spring.application.name=CloudNative_s1

# Conexión Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@mydatabase_high?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Oraclecloud123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Actuator
management.endpoints.web.exposure.include=health,info
server.port=8081